{
	"version": 1578298516,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/background-sheet0.png",
		"images/santa-sheet0.png",
		"images/endgame-sheet0.png",
		"images/replay-sheet0.png",
		"images/scorebg-sheet0.png",
		"images/highscore-sheet0.png",
		"images/score-sheet0.png",
		"images/sound-sheet0.png",
		"images/sound-sheet1.png",
		"images/ctreebottom-sheet0.png",
		"images/ctreetop-sheet0.png",
		"images/gift-sheet0.png",
		"images/gift-sheet1.png",
		"images/backtrees-sheet0.png",
		"images/cloud1-sheet0.png",
		"images/topline-sheet0.png",
		"images/deer-sheet0.png",
		"images/deer-sheet1.png",
		"images/taptoplay-sheet0.png",
		"media/button.m4a",
		"media/button.ogg",
		"media/merry christmas.m4a",
		"media/merry christmas.ogg",
		"media/snowing.m4a",
		"media/snowing.ogg",
		"media/present.m4a",
		"media/present.ogg",
		"media/lose.m4a",
		"media/lose.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}